### ISSUE TITLE
Allow Multiple File Paths

### ISSUE THREAD

**Issue by pjlamb12** [pjlamb12/runtime-config-loader#2]
Allow for multiple file paths being passed in for configuration to be loaded. This would be ideal for situations where a configuration file is saved in source control, but a local, untracked configuration file could also be used. The files would be loaded in the order in which they're passed, and merged together.

[deepmerge](https://www.npmjs.com/package/deepmerge) looks like the perfect package to help with this.

**Comment by webkhushboo** [comment]
If I have to add configs for different environments like prod , dev and stage and I have three files
1. config.dev.json
2. config.stage.json
3. config.prod.json

Then how would I load config json based upon the environments?

**Comment by pjlamb12** [comment]
Right now the idea is that on each server that you deploy the app to, like on your staging server or prod server, you would replace the config.json file and use that for the environment.

Allowing multiple files for configuration to be merged together is just an idea that I had in case multiple people on a team manage different parts of the configuration and want each part in its own file, for example.

**Comment by webkhushboo** [comment]
Thanks @pjlamb12  for clarification.
It means there is no such way to load the runtime config file as we have for environment.ts files.

**Comment by pjlamb12** [comment]
No, it's a different way of loading configuration than environment.ts files.

**Comment by sureshdotariya** [comment]
We can have RunTimeConfig 'configUrl' accepts array. Using forkjoin or mergemap observable, we can execute multiple files recursively and merge the result. Let me create PR for this

**Comment by vdolek** [comment]
If you still need this feature, my library [angular-runtime-config](https://github.com/vdolek/angular-runtime-config) supports that and some more.
